import { readFile, readdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

import sharp from 'sharp'

/**
 * One-shot asset preparation. Run manually, never in CI:
 *
 *     pnpm images:prepare
 *
 * It does two things:
 *
 * 1. Re-encodes every photograph in `public/images/` to the largest size the layout can
 *    actually display, using mozjpeg. Source files were arriving 2–4× larger than needed,
 *    which is slow on Vercel: the first request for each variant pays a cold optimisation,
 *    and the bigger the input the longer that takes.
 * 2. Regenerates `src/lib/images/blur.ts` — a 16px-wide base64 preview per image, used as
 *    a `placeholder="blur"`. That is what removes the visible "empty frame then photo"
 *    step, which is most of what "slow images" actually feels like.
 *
 * ⚠️ Re-encoding is lossy. Running this twice compresses already-compressed files, so the
 * script refuses to write when the result is not meaningfully smaller. Feed it originals.
 */

const IMAGES_DIR = 'public/images'
const BLUR_MODULE = 'src/lib/images/blur.ts'

/**
 * Max width per image, derived from the widest CSS box each one can occupy, doubled for
 * high-density screens and then capped where the extra detail stops being visible.
 */
const TARGETS = {
  'hero-mercedes-cls': { width: 2048, quality: 72 },
  'final-cta-bmw-m3-fog': { width: 2048, quality: 68 },

  // Before/after: the point is reading swirl marks, so keep the native resolution.
  'before-after-porsche-before': { width: 1376, quality: 80 },
  'before-after-porsche-after': { width: 1376, quality: 80 },

  'work-porsche-911': { width: 1800, quality: 74 },
  'work-amg-studio': { width: 1480, quality: 74 },
  'work-maserati': { width: 1200, quality: 74 },
  'work-alpine-a110': { width: 1100, quality: 74 },

  // Services show at 100vw on mobile and in a 320px preview on desktop.
  'service-paint-correction': { width: 1000, quality: 74 },
  'service-ceramic-coating': { width: 1000, quality: 74 },
  'service-interior': { width: 1000, quality: 74 },
  'service-full-detail': { width: 1000, quality: 74 },

  'og-default': { width: 1200, quality: 76 },
}

const kb = (bytes) => `${Math.round(bytes / 1024)}kB`

async function encode(inputPath, { width, quality }) {
  const input = await readFile(inputPath)
  const image = sharp(input)
  const meta = await image.metadata()

  return {
    meta,
    output: await image
      // `withoutEnlargement` matters: never upscale a source that is already smaller.
      .resize({ width, withoutEnlargement: true })
      .jpeg({ quality, mozjpeg: true, progressive: true, chromaSubsampling: '4:2:0' })
      .toBuffer(),
    before: input.length,
  }
}

async function main() {
  const files = (await readdir(IMAGES_DIR)).filter((name) => name.endsWith('.jpg')).sort()

  let totalBefore = 0
  let totalAfter = 0
  const blur = {}

  for (const file of files) {
    const slug = file.replace(/\.jpg$/, '')
    const target = TARGETS[slug]
    const path = join(IMAGES_DIR, file)

    if (!target) {
      console.log(`SKIP   ${file} — no target defined`)
      continue
    }

    const { meta, output, before } = await encode(path, target)

    // Refuse to lose quality for nothing if the file is already optimised.
    const worthwhile = output.length < before * 0.97
    if (worthwhile) await writeFile(path, output)

    totalBefore += before
    totalAfter += worthwhile ? output.length : before

    const note = worthwhile ? '' : '  (already optimal, kept)'
    console.log(
      `${worthwhile ? 'OK    ' : 'KEEP  '} ${file.padEnd(32)} ${meta.width}px → ${Math.min(target.width, meta.width)}px   ${kb(before)} → ${kb(worthwhile ? output.length : before)}${note}`,
    )

    // 16px wide is enough for a placeholder and keeps the base64 string short.
    const preview = await sharp(await readFile(path))
      .resize({ width: 16 })
      .jpeg({ quality: 40 })
      .toBuffer()

    blur[`/images/${file}`] = `data:image/jpeg;base64,${preview.toString('base64')}`
  }

  const entries = Object.entries(blur)
    .map(([key, value]) => `  '${key}': '${value}',`)
    .join('\n')

  await writeFile(
    BLUR_MODULE,
    `/**
 * GENERATED by scripts/prepare-images.mjs — do not edit by hand.
 *
 * A 16px-wide preview per photograph, inlined as base64 and used as next/image's
 * \`placeholder="blur"\`. Static string paths (as opposed to static imports) do not get a
 * blur placeholder automatically, so it is precomputed here.
 */
const BLUR_DATA: Record<string, string> = {
${entries}
}

/**
 * Spread onto a next/image to get a blur placeholder:
 * \`<Image src={src} {...blurProps(src)} />\`
 *
 * Returns nothing for an unknown path, so an image without a preview still renders.
 */
export function blurProps(src: string): { placeholder: 'blur'; blurDataURL: string } | undefined {
  const blurDataURL = BLUR_DATA[src]
  return blurDataURL ? { placeholder: 'blur', blurDataURL } : undefined
}
`,
  )

  console.log(
    `\nrazem: ${kb(totalBefore)} → ${kb(totalAfter)}  (−${Math.round((1 - totalAfter / totalBefore) * 100)}%)`,
  )
  console.log(`blur: ${entries.split('\n').length} wpisow -> ${BLUR_MODULE}`)
}

await main()
